### ISSUE TITLE
Verify the downscaling results

### ISSUE THREAD

**Issue by mahm1846** [OpheliaMiralles/wind-downscaling-gan#7]
I have installed and run wind downscaling notebook, from the following link: https://github.com/OpheliaMiralles/wind-downscaling-gan/blob/master/src/downscaling/wind_downscaling.ipynb

I am attaching a screenshot of the result.  Is the output look about correct? If not, can you provide some examples of the correct downscaled output? I hope to hear from you soon.

Best,
Maruf

<img width="913" alt="Screen Shot 2022-11-23 at 9 09 20 pm" src="https://user-images.githubusercontent.com/40089519/203521647-32aecd49-4b82-41fe-be46-dc102355e099.png">

**Comment by OpheliaMiralles** [comment]
Hi Maruf,

Thanks for your interest. The result looks fine to me, at least I don't see anything wrong. I'd like to emphasize that the model has been trained, validated, and tested using Switzerland wind fields. The downscaling of winds outside of Switzerland is experimental and cannot be guaranteed as correct.

Best,
Ophélia

**Comment by mahm1846** [comment]
Hi Ophélia,

Thanks very much for the reply. 
Do you have any script or notebook for new model training? 
If would be helpful if you can list the steps for training with other datasets.

Best,
Maruf

**Comment by OpheliaMiralles** [comment]
Hi Maruf, the model and its training are detailed in the following paper https://doi.org/10.1175/AIES-D-22-0018.1 <https://doi.org/10.1175/AIES-D-22-0018.1>.  New model training would imply to know the target winds for another geographical region, do you have COSMO-1 1km resolution winds (targets used to train this model, as explained in the paper) for the geographical region you are interest in? Otherwise, I cannot really help you… 
Best,
Ophélia

**Comment by mahm1846** [comment]
Hi Ophélia,

I am interested in the Australia region. Please, let me know if you can help in anyway.

Do you have plans to release other notebooks from your paper?
If would be much appreciated, if you do.

Best,
Maruf
